title: Samuel Zurowski's Website
description: "Website for blogging about my cybersecurity views/opinions"
author:
  name: "Samuel Zurowski"
  email: "szuro1@unh.newhaven.edu"
  url: "https://samuelzurowski.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-admin

# build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# admin stuff
jekyll_admin:
  hidden_links:
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "posts"


# Custom variables
owner : "samz"
year : "2021"

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Samuel H. Zurowski"
resume_title:                   "Cybersecurity Engineer"

resume_contact_email:           "szuro1@unh.newhaven.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "szuro1@unh.newhaven.edu"
display_header_contact_info:    "false"

resume_header_intro: >
  <p>
    Hello all, this website serves as a blog for me to post about my views, opinions, and
    lessons learned over the years. I really believe that writing about a topic can really help
    someone truly understand what is going on (and is why I started this). My interests are 
    almost anything related to cybersecurity so hopefully you'll see some helpful materials here!
  </p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false


resume_social_links:
  resume_github_url: >
    <a href="https://github.com/samuelzurowski/">https://github.com/samuelzurowski/</a>

  resume_twitter_url: >
    <a href="https://twitter.com/_Zen1x">https://twitter.com/_Zen1x/</a>

  # resume_dribbble_url:          "https://dribbble.com/jag"

  # resume_facebook_url:          "insert Facebook URL here"

  resume_linkedin_url: >
    <a href="https://www.linkedin.com/in/samuelzurowski/">https://www.linkedin.com/in/samuelzurowski/</a>
  # resume_instagram_url:         "insert your Instagram URL here"

  resume_website_url: >
    <a href="https://samuelzurowski.com">https://samuelzurowski.com</a>

  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
